server:
  port: 8080
javax:
  sql:
    DataSource:
      fieldserviceDataSource:
        dataSourceClassName: org.h2.jdbcx.JdbcDataSource
        dataSource: 
          url: jdbc:h2:file:./data/fieldService;INIT=RUNSCRIPT FROM 'classpath:fieldservice.ddl'
          user: sa
          password: ""
            