server:
  port: 8080
javax:
  sql:
    DataSource:
      fieldserviceDataSource:
        dataSourceClassName: com.mysql.cj.jdbc.MysqlDataSource
        dataSource: 
          url: jdbc:mysql://localhost:3306/fieldService
          user: root
          password: "oracle123@"
security:
  config:
    require-encryption: false
  
  providers:
    - http-basic-auth:
        realm: "fieldService"
        users:
          - login: "admin"
            password: "${CLEAR=admin}"
            roles: ["user", "admin"]
          - login: "user"
            password: "${CLEAR=password}"
            roles: ["user"]
    - http-digest-auth:
